import { createContext, useContext, useState, ReactNode } from 'react'

type Lang = 'fr' | 'en'
interface LangCtx { lang: Lang; t: (key: string) => string; toggleLang: () => void }

const T = {
  fr: {
    // NAV
    'nav.home':'Accueil','nav.about':'À Propos','nav.teachings':'Enseignements',
    'nav.videos':'Vidéos','nav.book':'Mon Livre','nav.blog':'Blog',
    'nav.more':'Plus','nav.xassida':'Xassida',
    'nav.mission':'Mission du Cheikh','nav.economy':'Modèle Économique',
    'nav.quotes':'Citations','nav.gallery':'Galerie','nav.contact':'Contact',
    'nav.institut':'The Project','nav.khassaides':'Historical Khassaïdes',
    'nav.evenements':'Mouride Events','nav.khalifes':'Khalifes of Serigne Touba',
    'nav.podcast':'Podcast','nav.actualites':'News',
    // HERO
    'hero.bismillah':'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم',
    'hero.subtitle':'Transmettre la pensée de Cheikh Ahmadou Bamba à la jeunesse',
    'hero.quote':'Ô vous les adolescents ! ne vous préoccupez que de droiture, évertuez-vous à la recherche du savoir.',
    'hero.quoteAuthor':'Cheikh Ahmadou Bamba - Viatique des Adolescents',
    'hero.cta1':'Découvrir les Enseignements','hero.cta2':'En Savoir Plus',
    'hero.missionLabel':'Notre Mission',
    'hero.mission':'"Transmettre les valeurs de foi, de travail et de service à travers la pensée mouride."',
    // ABOUT
    'about.tag':'Découvrez','about.title':'À Propos',
    'about.r1title':'Étudiant en Master',
    'about.r1desc':"Sciences de l'Éducation et Technologies Éducatives - Passionné par l'innovation, le numérique et la transmission du savoir.",
    'about.r2title':'Entrepreneur Tech & Auteur',
    'about.r2desc':"Auteur de l'ouvrage le leadership de Cheikh Ahmadou Bamba, engagé dans l'entrepreneuriat technologie, éducatif, Santé...",
    'about.r3title':'Fondateur du Mouvement des Élites Mourides',
    'about.r3desc':"Une initiative dédiée à rassembler et former la jeunesse autour des valeurs de foi, de travail et d'excellence.",
    'about.r4title':'Vulgarisateur de la Pensée Mouride',
    'about.r4desc':"Engagé dans la transmission et l'explication des enseignements de Cheikh Ahmadou Bamba auprès des nouvelles générations.",
    'about.imgCaption':'Mosquée de Touba – Symbole de la foi mouride',
    'about.objectiveTitle':"Qu'est-ce qu'Étudiant Mouride ?",
    'about.objective1':"Étudiant Mouride est une initiative intellectuelle et éducative qui vise à étudier, comprendre et transmettre la pensée, l'enseignement et la vision de société de Cheikh Ahmadou Bamba.",
    'about.objective2':"Ce projet s'inscrit dans une volonté de mettre en lumière la richesse spirituelle, intellectuelle et civilisationnelle du mouridisme, en proposant un espace de réflexion, d'apprentissage et de transmission autour de l'héritage de Khadimou Rassoul.",
    'about.objective3':"Son objectif est de rendre cet héritage plus accessible aux nouvelles générations, en utilisant les outils modernes du savoir, de l'éducation et du numérique, afin de favoriser une meilleure compréhension de la mission du Cheikh et de la profondeur de sa pensée.",
    'about.objective4':"À travers cette initiative, Étudiant Mouride cherche également à explorer et à expliquer les différentes dimensions de la pensée de Cheikh Ahmadou Bamba : sa vision spirituelle, son modèle de société fondé sur la foi, le travail et le service, son approche du leadership, ainsi que sa contribution à la dignité et à la renaissance intellectuelle africaine.",
    'about.objective5':"Dans un monde marqué par de nombreux défis sociaux, éducatifs et moraux, Étudiant Mouride ambitionne aussi de montrer comment les principes et les valeurs portés par le Cheikh peuvent inspirer des réponses aux défis actuels, notamment dans les domaines de l'éducation, du développement, de l'éthique, du leadership et de la construction d'une société plus juste et responsable.",
    'about.objective6':"À terme, cette initiative aspire à devenir un espace de référence pour l'étude, la compréhension et la transmission de la pensée de Cheikh Ahmadou Bamba, en contribuant à préserver cet héritage et à le faire découvrir à un public toujours plus large.",
    'about.exploreTitle':'À travers cette plateforme, Étudiant Mouride explore et explique :',
    'about.e1':"La mission spirituelle de Cheikh Ahmadou Bamba",
    'about.e2':"Sa philosophie de la foi, du travail et du service",
    'about.e3':"Son modèle de société fondé sur la discipline, la connaissance et l'éthique",
    'about.e4':"Sa vision économique et sociale",
    'about.e5':"Son rôle dans la dignité et la renaissance intellectuelle africaine",
    'about.challenge':"Cette pensée peut contribuer à répondre aux défis actuels de nos sociétés, notamment en matière d'éducation, de développement, de leadership, d'éthique et de responsabilité.",
    'about.ambitionTitle':"L'ambition d'Étudiant Mouride :",
    'about.a1':"Un espace de transmission du savoir",
    'about.a2':"Une bibliothèque intellectuelle autour de la pensée du Cheikh",
    'about.a3':"Un lieu d'analyse et de réflexion",
    'about.a4':"Une université numérique dédiée à l'étude du mouridisme et de la pensée de Cheikh Ahmadou Bamba",
    // TEACHINGS
    'teach.tag':'Apprendre','teach.title':'Enseignements',
    'teach.subtitle':'Explorez les thèmes fondamentaux de la philosophie mouride et découvrez la sagesse de Cheikh Ahmadou Bamba.',
    'teach.readmore':'Lire plus',
    'teach.faith.title':'La Foi (Iman)',
    'teach.faith.desc':"La foi est le fondement de toute la pensée de Cheikh Ahmadou Bamba. Il enseignait que la véritable foi transforme l'âme et guide vers l'excellence.",
    'teach.work.title':'Le Travail (Ligééy)',
    'teach.work.desc':"Le travail est une adoration dans la philosophie mouride. Cheikh Ahmadou Bamba a élevé le travail au rang d'acte spirituel et de voie vers l'autonomie.",
    'teach.service.title':'Le Service (Dieureudieuf)',
    'teach.service.desc':"Servir les autres et sa communauté est une valeur centrale. Le service désintéressé est considéré comme une forme d'adoration et de purification.",
    'teach.edu.title':"L'Éducation (Tarbiya)",
    'teach.edu.desc':"L'éducation spirituelle et intellectuelle est au cœur de la mission du Cheikh. Il a fondé des daaras pour former des générations d'érudits.",
    'teach.lead.title':'Le Leadership',
    'teach.lead.desc':"Le leadership selon Cheikh Ahmadou Bamba est basé sur l'humilité, la sagesse et le service. Un vrai leader est celui qui élève les autres.",
    'teach.patience.title':'La Patience (Sabaru)',
    'teach.patience.desc':"La patience face aux épreuves est une vertu suprême dans les enseignements du Cheikh. Elle est la clé de la résilience et de la victoire spirituelle.",
    // VIDEOS
    'videos.tag':'Regarder','videos.title':'Vidéos Éducatives',
    'videos.subtitle':'Capsules pédagogiques expliquant les enseignements de Cheikh Ahmadou Bamba.',
    'videos.ep1.label':'Épisode 1','videos.ep1.title':"La formation et l'éducation",
    'videos.ep1.desc':"Découvrez les fondements de l'éducation et de la formation dans le mouridisme.",
    'videos.ep2.label':'Épisode 2','videos.ep2.title':'La lutte de Cheikh Ahmadou Bamba pour la dignité noire',
    'videos.ep2.desc':"Affirmation de l'identité africaine",
    'videos.ep3.label':'Épisode 3','videos.ep3.title':'Mouvement des Elites Mourides',
    'videos.ep3.desc':'Comprendre la mission spirituelle de Serigne Touba.',
    'videos.cta':'Voir toutes les vidéos sur YouTube',
    // BOOK
    'book.tag':'Publication','book.title':'Mon Livre',
    'book.bookTitle':'Le Leadership de Cheikh Ahmadou Bamba',
    'book.desc':"Cet ouvrage explore les principes de leadership éthique et spirituel tirés des enseignements de Cheikh Ahmadou Bamba.",
    'book.themes':'Thèmes abordés :',
    'book.t1':'Les fondements du leadership de Cheikh Ahmadou Bamba',
    'book.t2':'La vision spirituelle de Cheikh Ahmadou Bamba',
    'book.t3':'Un Modèle de Dévotion','book.t4':'Les Enseignements Pérennes du Cheikh',
    'book.t5':'Leadership en Action','book.t6':"L'Héritage du Cheikh",
    'book.download':'Télécharger un extrait','book.preview':'Lire un aperçu',
    // XASSIDA
    'xassida.tag':'Écouter','xassida.title':'Sons de Xassida',
    'xassida.subtitle':'Écoutez les poèmes spirituels (Khassaïdes) de Cheikh Ahmadou Bamba, récités avec dévotion.',
    'xassida.r1':'Récitateur : Kourel Hizbut Tarkhiyah','xassida.r2':'Récitateur : Kourel 1 HTDKH',
    'xassida.r3':'Récitateur : Kourel Tout Tankh','xassida.r4':'Récitateur : Kourel HTDKH',
    'xassida.d1':"L'attraction des cœurs – Un poème sur l'amour divin et la dévotion spirituelle.",
    'xassida.d2':"La quête des deux bonheurs – Guidance pour le succès ici-bas et dans l'au-delà.",
    'xassida.d3':'Les voies du Paradis – Guide spirituel vers les chemins de la félicité éternelle.',
    'xassida.d4':"L'illuminateur des poitrines – Poème sur la lumière de la foi et de la connaissance.",
    // LIBRARY
    'lib.tag':'Bibliothèque','lib.title':'Livres sur Cheikh Ahmadou Bamba',
    'lib.subtitle':"Sélection d'ouvrages pour mieux comprendre la vie et les enseignements du Cheikh.",
    'lib.b1title':'Guide du Mouridisme',
    'lib.b1desc':'Ce petit livre vous permettra de découvrir les villes qui ont marqué la naissance du mouridisme.',
    'lib.b2title':"LES BIENFAITS DE L'ÉTERNEL",
    'lib.b2desc':'« Minanoul Bakhil Khadim fi Siratoul Cheikh al-Khadim »',
    'lib.b3title':'Les Khassaides de Serigne Touba',
    'lib.b3desc':'DIEUREUDIEUFFÉ SERIGNE TOUBA!!!',
    'lib.b4title':'Diazbul Mouride','lib.b4desc':'Par Cheikh Ibrahima FALL',
    'lib.read':'Lire le livre →',
    // MISSION
    'mission.tag':'Histoire & Vision','mission.title':'La Mission du Cheikh',
    'mission.subtitle':'Quelle était la mission de Cheikh Ahmadou Bamba ? Découvrez son combat spirituel, sa résistance pacifique et sa vision de transformation sociale.',
    'mission.intro':"Cheikh Ahmadou Bamba Mbacké (1853–1927) était un réformateur religieux, un érudit islamique et un leader spirituel sénégalais. Sa mission transcendait la simple transmission du savoir religieux pour englober une vision globale de transformation individuelle et sociale.",
    'mission.pillars':'Les Quatre Piliers de sa Mission',
    'mission.p1.title':'Combat Spirituel',
    'mission.p1.desc':"Le Cheikh a mené un jihad spirituel basé sur l'éducation, la purification de l'âme et le rapprochement avec le divin.",
    'mission.p1.l1':"Purification de l'âme (Tazkiya)",
    'mission.p1.l2':'Éducation spirituelle (Tarbiya)',
    'mission.p1.l3':'Dhikr et invocations constantes',
    'mission.p1.l4':'Amour du Prophète Muhammad (PSL)',
    'mission.p2.title':'Résistance Pacifique',
    'mission.p2.desc':"Face au colonialisme français, le Cheikh a choisi la résistance non-violente, refusant toute collaboration tout en évitant l'affrontement armé.",
    'mission.p2.l1':'Rejet de la collaboration coloniale',
    'mission.p2.l2':'Dignité et fierté africaine',
    'mission.p2.l3':"Résistance par l'éducation",
    'mission.p2.l4':'Organisation autonome de la communauté',
    'mission.p3.title':'Réforme de la Société',
    'mission.p3.desc':"Le Cheikh a proposé un modèle de société basé sur des valeurs islamiques et des principes d'organisation sociale novateurs.",
    'mission.p3.l1':'Valorisation du travail (Ligééy)',
    'mission.p3.l2':'Solidarité communautaire',
    'mission.p3.l3':'Autonomie économique',
    'mission.p3.l4':'Justice sociale et équité',
    'mission.p4.title':'Dignité Noire',
    'mission.p4.desc':"À une époque de domination coloniale, le Cheikh a affirmé la dignité et la valeur intrinsèque des Africains noirs.",
    'mission.p4.l1':"Fierté de l'identité noire",
    'mission.p4.l2':"Rejet de l'infériorisation",
    'mission.p4.l3':'Excellence intellectuelle',
    'mission.p4.l4':'Autonomie culturelle et spirituelle',
    'mission.timeline':'Frise Historique',
    'mission.t1':'Naissance à Mbacké Baol','mission.t1sub':"Début d'une vie exceptionnelle",
    'mission.t2':'Exil au Gabon','mission.t2sub':'Résistance pacifique',
    'mission.t3':"Retour d'exil",'mission.t3sub':'Renforcement de la communauté',
    'mission.t4':'Fondation de Touba','mission.t4sub':'Création de la cité sainte',
    'mission.t5':'Rappel à Dieu','mission.t5sub':'Héritage spirituel éternel',
    'mission.quote':"Mon combat n'est pas contre les hommes, mais contre l'ignorance et l'injustice",
    'mission.legacy':"La mission de Cheikh Ahmadou Bamba continue d'inspirer des millions de personnes à travers le monde.",
    // ECONOMY
    'eco.tag':'Économie & Société','eco.title':'Modèle Économique Mouride',
    'eco.subtitle':"Un système économique innovant basé sur le travail, la solidarité et l'autonomie.",
    'eco.lab.title':'Un Laboratoire Économique Unique',
    'eco.lab.p1':"Le modèle économique mouride représente une expérience sociale et économique unique en Afrique. Il combine des principes spirituels avec une organisation pragmatique.",
    'eco.lab.p2':"Ce système a démontré sa résilience pendant plus d'un siècle, transformant des territoires arides en zones productives.",
    'eco.stat1':'Années de résilience économique','eco.stat2':'Membres dans la diaspora mondiale',
    'eco.stat3':'2ème ville du Sénégal','eco.stat4':'Solidarité communautaire',
    'eco.principles':'Principes Économiques Fondamentaux',
    'eco.p1.title':'Le Travail comme Valeur Centrale',
    'eco.p1.desc':"Dans le mouridisme, le travail est une forme d'adoration et un chemin vers l'autonomie.",
    'eco.impacts':'Impacts concrets',
    'eco.p1.l1':"Transformation de terres arides en terres fertiles",
    'eco.p1.l2':"Création de richesse collective par la discipline",
    'eco.p1.l3':"Modèle d'entrepreneuriat spirituel unique",
    'eco.p1.l4':"Autonomie économique de la communauté mouride",
    'eco.p2.title':'Solidarité et Entraide',
    'eco.p2.desc':'Le système mouride repose sur des mécanismes de solidarité puissants : redistribution des richesses et soutien mutuel.',
    'eco.p2.l1':'Réseau mondial de solidarité entre mourides',
    'eco.p2.l2':'Système de financement communautaire (dahira)',
    'eco.p2.l3':'Soutien aux entrepreneurs et jeunes diplômés',
    'eco.p2.l4':'Redistribution équitable des ressources',
    'eco.p3.title':'Organisation Économique de Touba',
    'eco.p3.desc':"Touba est devenue une ville économique majeure du Sénégal, avec un modèle d'organisation unique.",
    'eco.charact':'Caractéristiques',
    'eco.p3.l1':'2ème ville économique du Sénégal',
    'eco.p3.l2':'Marché international Ocass de renommée mondiale',
    'eco.p3.l3':'Infrastructure développée par la communauté',
    'eco.p3.l4':'Modèle de gouvernance participative unique',
    // QUOTES
    'cit.tag':'Sagesse','cit.title':'Citations Inspirantes',
    'cit.q1':"Ne sacrifie pas l'au-delà pour ce monde, ô fils d'Adam. Quiconque échange la lumière pour l'obscurité le regrettera.",
    'cit.q2':"N'abusez pas de ma condition d'homme noir, car je suis le serviteur éternel du prophète Mohamed (PSL) et chaque génération aura la certitude que je suis venu pour elle.",
    'cit.q3':"Ne te plains pas tout le temps des épreuves. Sois courageux et agis de telle sorte que les gens croient que tu ne manques de rien.",
    'cit.q4':"Je rends grâce à mon Seigneur, le Meilleur Éducateur. Qui a parfait mon cœur à travers l'imitation du Prophète, le Modèle par Excellence.",
    'cit.q5':"Essaie toujours de te cacher toi qui est à la quête du savoir. Aie de la détermination ainsi tu dépasseras ta génération.",
    'cit.q6':"Ne consomme pas l'illicite ni le douteux. Consomme le licite. Car quiconque gaspille le licite sera gaspillé.",
    'cit.src1':'Kun Katiman','cit.src2':'Maasalikul Jinaane','cit.src3':'Kun Katiman',
    'cit.src4':'Muwahibi','cit.src5':'Kun Katiman','cit.src6':'Munawwir-us-sudûr',
// GALLERY
    'gallery.tag':'Images','gallery.title':'Galerie',
    'gallery.subtitle':"Visuels et images liés au mouridisme et à l'héritage spirituel de Cheikh Ahmadou Bamba.",
    'gallery.p1.title':'Gare de Louga – 20 Août 1895',
    'gallery.p1.desc':"Cheikh Ahmadou Bamba pria à la gare de Louga le 20 Août 1895. Le 5 septembre 1895 à Saint Louis, il fut jugé et déporté au Gabon, quittant le Sénégal le 21 Septembre 1895 à bord du navire «Ville de Pernambouc».",
    'gallery.p2.title':'Magal de Touba',
    'gallery.p2.desc':"Le Grand Magal, pèlerinage annuel rassemblant des millions de fidèles à Touba.",
    'gallery.p3.title':'Darou Marnane',
    'gallery.p3.desc':"Fondé par Mame Thierno sur recommandation de Serigne Touba, qui à son retour du Gabon résida (1902-1903) à Darou Marnane. Le 14 juin 1903, il sera encerclé par les autorités coloniales et déporté en Mauritanie.",
    'gallery.p4.title':'Serigne Touba et Cheikh Ibra',
    'gallery.p4.desc':"Portrait historique de Cheikh Ahmadou Bamba et Cheikh Ibrahima Fall, pilier du mouridisme.",
    'gallery.p5.title':'Serigne Mountakha Mbacké',
    'gallery.p5.desc':"Serigne Mountakha Mbacké, Khalife Général des Mourides, guide spirituel de la communauté.",
    'gallery.p6.title':'Thieyene Djolof',
    'gallery.p6.desc':"Village où Cheikh Ahmadou Bamba à son retour d'exil de Mauritanie (1907-1912) fut assigné à résidence. Cheikh Abdoulahi Mbacké (Serigne Abdou Borom Deurbi) y est né.",
    'gallery.p7.title':'Darou Mousty',
    'gallery.p7.desc':"Fondée par Mame Thierno Birahim Mbacké en 1912 sur instruction de son frère Ahmadou Bamba. Darou Mousty est une ville religieuse mouride située à 28 km de Touba, dans la région de Louga.",
    'gallery.p8.title':'Touba – Cité Sainte',
    'gallery.p8.desc':"Fondée en 1887-1888 par Cheikh Ahmadou Bamba, Touba est la capitale du mouridisme. Née d'une vision mystique dans la forêt de Mbaffar, elle est aujourd'hui la deuxième ville du Sénégal.",
    // BLOG
    'blog.tag':'Actualités','blog.title':'Blog Mouride',
    'blog.subtitle':'Articles, réflexions et actualités sur la spiritualité mouride et la jeunesse africaine.',
    'blog.all':'Tous','blog.spiritualite':'Spiritualité','blog.leadership':'Leadership',
    'blog.economie':'Économie','blog.jeunesse':'Jeunesse','blog.histoire':'Histoire',
    'blog.readmore':"Lire l'article →",
    'blog.newsletter.title':'Restez informé des nouveaux articles',
    'blog.newsletter.desc':'Recevez chaque semaine nos meilleurs articles sur la spiritualité mouride.',
    'blog.newsletter.ph':'votre@email.com','blog.newsletter.btn':"S'abonner",
    'blog.newsletter.success':'✓ Merci ! Vous êtes abonné(e).',
    'blog.reactions':'Réactions','blog.comments':'Commentaires',
    'blog.commentBtn':'Publier','blog.firstComment':'Soyez le premier à commenter ✨',
    // CONTACT
    'contact.tag':'Contactez-nous','contact.title':'Contact',
    'contact.subtitle':'Restons en contact',
    'contact.desc':"Pour toute question, collaboration ou suggestion, n'hésitez pas à nous contacter.",
    'contact.nameLabel':'Nom complet','contact.namePH':'Votre nom',
    'contact.emailLabel':'Email','contact.subjectLabel':'Sujet',
    'contact.subjectPH':'Sujet de votre message',
    'contact.msgLabel':'Message','contact.msgPH':'Votre message...',
    'contact.send':'Envoyer le message','contact.follow':'Suivez-nous',
    'contact.successMsg':'Message envoyé avec succès !',
    'contact.successSub':'Nous vous répondrons dans les plus brefs délais.',
    // FOOTER
    'footer.links':'Liens rapides',
    'footer.desc':"Étudiant Mouride Academy - Plateforme dédiée à la transmission de la pensée de Cheikh Ahmadou Bamba à la jeunesse.",
    'footer.copy':'© 2026 Étudiant Mouride Academy | MS',
  },
  en: {
    // NAV
    'nav.home':'Home','nav.about':'About','nav.teachings':'Teachings',
    'nav.videos':'Videos','nav.book':'My Book','nav.blog':'Blog',
    'nav.more':'More','nav.xassida':'Xassida',
    'nav.mission':"The Sheikh's Mission",'nav.economy':'Mouride Economic Model',
    'nav.quotes':'Quotes','nav.gallery':'Gallery','nav.contact':'Contact',
    'nav.institut':'The Project','nav.khassaides':'Historical Khassaïdes',
    'nav.evenements':'Mouride Events','nav.khalifes':'Khalifes of Serigne Touba',
    'nav.podcast':'Podcast','nav.actualites':'News',
    // HERO
    'hero.bismillah':'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيم',
    'hero.subtitle':'Spreading the thought of Cheikh Ahmadou Bamba to the youth',
    'hero.quote':'O you adolescents! Concern yourselves only with righteousness, strive earnestly in the pursuit of knowledge.',
    'hero.quoteAuthor':'Cheikh Ahmadou Bamba - Viatique des Adolescents',
    'hero.cta1':'Discover the Teachings','hero.cta2':'Learn More',
    'hero.missionLabel':'Our Mission',
    'hero.mission':'"Transmitting the values of faith, work and service through Mouride thought."',
    // ABOUT
    'about.tag':'Discover','about.title':'About',
    'about.r1title':"Master's Student",
    'about.r1desc':'Educational Sciences and Educational Technologies - Passionate about innovation, digital tools, and knowledge transmission.',
    'about.r2title':'Tech Entrepreneur & Author',
    'about.r2desc':'Author of a book on the leadership of Cheikh Ahmadou Bamba, engaged in technology, education, and health entrepreneurship.',
    'about.r3title':'Founder of the Mouride Elites Movement',
    'about.r3desc':'An initiative dedicated to gathering and training youth around the values of faith, work, and excellence.',
    'about.r4title':'Mouride Thought Popularizer',
    'about.r4desc':'Committed to transmitting and explaining the teachings of Cheikh Ahmadou Bamba to new generations.',
    'about.imgCaption':'Mosque of Touba – Symbol of Mouride faith',
    'about.objectiveTitle':'What is Étudiant Mouride?',
    'about.objective1':'Étudiant Mouride is an intellectual and educational initiative that aims to study, understand and transmit the thought, teaching and social vision of Cheikh Ahmadou Bamba.',
    'about.objective2':'Its objective is to make this spiritual, intellectual and civilizational heritage accessible to new generations, using modern tools of knowledge and digital technology.',
    'about.objective3':'This project is part of a desire to highlight the spiritual, intellectual and civilizational richness of Mouridism, offering a space for reflection, learning and transmission around the heritage of Khadimou Rassoul.',
    'about.objective4':'Through this initiative, Étudiant Mouride also seeks to explore and explain the different dimensions of the thought of Cheikh Ahmadou Bamba: his spiritual vision, his social model based on faith, work and service, his approach to leadership, and his contribution to African dignity and intellectual renaissance.',
    'about.objective5':'In a world marked by many social, educational and moral challenges, Étudiant Mouride also aims to show how the principles and values carried by the Sheikh can inspire responses to current challenges, particularly in education, development, ethics, leadership and building a more just and responsible society.',
    'about.objective6':'Ultimately, this initiative aspires to become a reference space for the study, understanding and transmission of the thought of Cheikh Ahmadou Bamba, contributing to preserving this heritage and making it known to an ever wider audience.',
    'about.exploreTitle':'Through this platform, Étudiant Mouride explores and explains:',
    'about.e1':'The spiritual mission of Cheikh Ahmadou Bamba',
    'about.e2':'His philosophy of faith, work and service',
    'about.e3':'His social model based on discipline, knowledge and ethics',
    'about.e4':'His economic and social vision',
    'about.e5':'His role in African dignity and intellectual renaissance',
    'about.challenge':'This thought can help address current societal challenges, particularly in education, development, leadership, ethics and responsibility.',
    'about.ambitionTitle':'The ambition of Étudiant Mouride:',
    'about.a1':'A space for knowledge transmission',
    'about.a2':'An intellectual library around the thought of the Sheikh',
    'about.a3':'A place for analysis and reflection',
    'about.a4':'A digital university dedicated to the study of Mouridism and the thought of Cheikh Ahmadou Bamba',
    // TEACHINGS
    'teach.tag':'Learn','teach.title':'Teachings',
    'teach.subtitle':'Explore the fundamental themes of Mouride philosophy and discover the wisdom of Cheikh Ahmadou Bamba.',
    'teach.readmore':'Read more',
    'teach.faith.title':'Faith (Iman)',
    'teach.faith.desc':'Faith is the foundation of all of Cheikh Ahmadou Bamba\'s thought. He taught that true faith transforms the soul and guides toward excellence.',
    'teach.work.title':'Work (Ligééy)',
    'teach.work.desc':'Work is a form of worship in Mouride philosophy. Cheikh Ahmadou Bamba elevated work to the rank of spiritual act and path to autonomy.',
    'teach.service.title':'Service (Dieureudieuf)',
    'teach.service.desc':'Serving others and one\'s community is a central value. Selfless service is considered a form of worship and purification.',
    'teach.edu.title':'Education (Tarbiya)',
    'teach.edu.desc':'Spiritual and intellectual education is at the heart of the Sheikh\'s mission. He founded daaras to train generations of scholars.',
    'teach.lead.title':'Leadership',
    'teach.lead.desc':'Leadership according to Cheikh Ahmadou Bamba is based on humility, wisdom and service. A true leader is one who elevates others.',
    'teach.patience.title':'Patience (Sabaru)',
    'teach.patience.desc':'Patience in the face of trials is a supreme virtue in the Sheikh\'s teachings. It is the key to resilience and spiritual victory.',
    // VIDEOS
    'videos.tag':'Watch','videos.title':'Educational Videos',
    'videos.subtitle':'Short educational videos explaining the teachings of Cheikh Ahmadou Bamba.',
    'videos.ep1.label':'Episode 1','videos.ep1.title':'Training and Education',
    'videos.ep1.desc':'Discover the foundations of education and training in Mouridism.',
    'videos.ep2.label':'Episode 2','videos.ep2.title':"Cheikh Ahmadou Bamba's struggle for Black dignity",
    'videos.ep2.desc':'Affirmation of African identity',
    'videos.ep3.label':'Episode 3','videos.ep3.title':'Mouride Elites Movement',
    'videos.ep3.desc':'Understanding the spiritual mission of Serigne Touba.',
    'videos.cta':'See all videos on YouTube',
    // BOOK
    'book.tag':'Publication','book.title':'My Book',
    'book.bookTitle':'The Leadership of Cheikh Ahmadou Bamba',
    'book.desc':'This work explores the principles of ethical and spiritual leadership drawn from the teachings of Cheikh Ahmadou Bamba.',
    'book.themes':'Topics covered:',
    'book.t1':'The foundations of leadership of Cheikh Ahmadou Bamba',
    'book.t2':'The spiritual vision of Cheikh Ahmadou Bamba',
    'book.t3':'A Model of Devotion','book.t4':"The Sheikh's Eternal Teachings",
    'book.t5':'Leadership in Action','book.t6':"The Sheikh's Legacy",
    'book.download':'Download an excerpt','book.preview':'Read a preview',
    // XASSIDA
    'xassida.tag':'Listen','xassida.title':'Xassida Sounds',
    'xassida.subtitle':'Listen to the spiritual poems (Khassaïdes) of Cheikh Ahmadou Bamba, recited with devotion.',
    'xassida.r1':'Reciter: Kourel Hizbut Tarkhiyah','xassida.r2':'Reciter: Kourel 1 HTDKH',
    'xassida.r3':'Reciter: Kourel Tout Tankh','xassida.r4':'Reciter: Kourel HTDKH',
    'xassida.d1':'The attraction of hearts - A poem on divine love and spiritual devotion.',
    'xassida.d2':'The quest for two happinesses - Guidance for success in this world and the hereafter.',
    'xassida.d3':'The paths of Paradise - Spiritual guide toward eternal bliss.',
    'xassida.d4':'The illuminator of chests - Poem on the light of faith and knowledge.',
    // LIBRARY
    'lib.tag':'Library','lib.title':'Books about Cheikh Ahmadou Bamba',
    'lib.subtitle':'A selection of works to better understand the life and teachings of the Sheikh.',
    'lib.b1title':'Guide to Mouridism',
    'lib.b1desc':'This small book will allow you to discover the cities that marked the birth of Mouridism.',
    'lib.b2title':"THE ETERNAL'S BLESSINGS",
    'lib.b2desc':'« Minanoul Bakhil Khadim fi Siratoul Cheikh al-Khadim »',
    'lib.b3title':'The Khassaïdes of Serigne Touba',
    'lib.b3desc':'DIEUREUDIEUFFÉ SERIGNE TOUBA!!!',
    'lib.b4title':'Diazbul Mouride','lib.b4desc':'By Cheikh Ibrahima FALL',
    'lib.read':'Read the book →',
    // MISSION
    'mission.tag':'History & Vision','mission.title':"The Sheikh's Mission",
    'mission.subtitle':'What was the mission of Cheikh Ahmadou Bamba? Discover his spiritual struggle, peaceful resistance, and vision of social transformation.',
    'mission.intro':'Cheikh Ahmadou Bamba Mbacké (1853–1927) was a religious reformer, Islamic scholar, and Senegalese spiritual leader. His mission transcended mere religious knowledge transmission to encompass a global vision of individual and social transformation.',
    'mission.pillars':'The Four Pillars of His Mission',
    'mission.p1.title':'Spiritual Struggle',
    'mission.p1.desc':'The Sheikh led a spiritual jihad based on education, purification of the soul, and drawing closer to the divine.',
    'mission.p1.l1':'Purification of the soul (Tazkiya)',
    'mission.p1.l2':'Spiritual education (Tarbiya)',
    'mission.p1.l3':'Dhikr and constant invocations',
    'mission.p1.l4':'Love for the Prophet Muhammad (PBUH)',
    'mission.p2.title':'Peaceful Resistance',
    'mission.p2.desc':'Faced with French colonialism, the Sheikh chose non-violent resistance, refusing collaboration while avoiding armed confrontation.',
    'mission.p2.l1':'Rejection of colonial collaboration',
    'mission.p2.l2':'African dignity and pride',
    'mission.p2.l3':'Resistance through education',
    'mission.p2.l4':'Autonomous organization of the community',
    'mission.p3.title':'Social Reform',
    'mission.p3.desc':'The Sheikh proposed a social model based on Islamic values and innovative organizational principles.',
    'mission.p3.l1':'Valorization of work (Ligééy)',
    'mission.p3.l2':'Community solidarity',
    'mission.p3.l3':'Economic autonomy',
    'mission.p3.l4':'Social justice and equity',
    'mission.p4.title':'Black Dignity',
    'mission.p4.desc':'In an era of colonial domination, the Sheikh affirmed the dignity and intrinsic value of Black Africans.',
    'mission.p4.l1':'Pride in Black identity',
    'mission.p4.l2':'Rejection of inferiorization',
    'mission.p4.l3':'Intellectual excellence',
    'mission.p4.l4':'Cultural and spiritual autonomy',
    'mission.timeline':'Historical Timeline',
    'mission.t1':'Birth in Mbacké Baol','mission.t1sub':'Beginning of an exceptional life',
    'mission.t2':'Exile to Gabon','mission.t2sub':'Peaceful resistance',
    'mission.t3':'Return from exile','mission.t3sub':'Strengthening the community',
    'mission.t4':'Founding of Touba','mission.t4sub':'Creation of the holy city',
    'mission.t5':'Passing away','mission.t5sub':'Eternal spiritual legacy',
    'mission.quote':'My struggle is not against men, but against ignorance and injustice',
    'mission.legacy':'The mission of Cheikh Ahmadou Bamba continues to inspire millions of people around the world.',
    // ECONOMY
    'eco.tag':'Economy & Society','eco.title':'The Mouride Economic Model',
    'eco.subtitle':'An innovative economic system based on work, solidarity, and autonomy.',
    'eco.lab.title':'A Unique Economic Laboratory',
    'eco.lab.p1':'The Mouride economic model represents a unique social and economic experience in Africa, combining spiritual principles with pragmatic organization.',
    'eco.lab.p2':'This system has demonstrated its resilience for over a century, transforming arid territories into productive zones.',
    'eco.stat1':'Years of economic resilience','eco.stat2':'Members in the global diaspora',
    'eco.stat3':'2nd city of Senegal','eco.stat4':'Community solidarity',
    'eco.principles':'Core Economic Principles',
    'eco.p1.title':'Work as a Core Value',
    'eco.p1.desc':'In Mouridism, work is a form of worship and a path to autonomy.',
    'eco.impacts':'Concrete Impacts',
    'eco.p1.l1':'Transformation of arid land into fertile fields',
    'eco.p1.l2':'Creation of collective wealth through discipline',
    'eco.p1.l3':'Unique model of spiritual entrepreneurship',
    'eco.p1.l4':'Economic autonomy of the Mouride community',
    'eco.p2.title':'Solidarity and Mutual Aid',
    'eco.p2.desc':'The Mouride system relies on powerful solidarity mechanisms: wealth redistribution and mutual support among disciples.',
    'eco.p2.l1':'Global solidarity network among Mourides',
    'eco.p2.l2':'Community financing system (dahira)',
    'eco.p2.l3':'Support for entrepreneurs and young graduates',
    'eco.p2.l4':'Equitable redistribution of resources',
    'eco.p3.title':'Economic Organization of Touba',
    'eco.p3.desc':'Touba has become a major economic city of Senegal, with a unique organizational model based on Mouride principles.',
    'eco.charact':'Characteristics',
    'eco.p3.l1':'2nd economic city of Senegal',
    'eco.p3.l2':'International Ocass market of worldwide renown',
    'eco.p3.l3':'Infrastructure developed by the community',
    'eco.p3.l4':'Unique participatory governance model',
    // QUOTES
    'cit.tag':'Wisdom','cit.title':'Inspiring Quotes',
    'cit.q1':"Do not sacrifice the hereafter for this world, O son of Adam. Whoever exchanges light for darkness will regret it.",
    'cit.q2':"Do not abuse my condition as a Black man, for I am the eternal servant of the Prophet Muhammad (PBUH) and every generation will be certain that I came for it.",
    'cit.q3':"Do not always complain about your trials. Be courageous and act so that people believe you lack nothing.",
    'cit.q4':"I give thanks to my Lord, the Best Educator, who perfected my heart through imitation of the Prophet, the Supreme Model.",
    'cit.q5':"Always try to remain humble in your quest for knowledge. Have determination and you will surpass your generation.",
    'cit.q6':"Do not consume the forbidden or the doubtful. Consume only the lawful. For whoever wastes the lawful will be wasted.",
    'cit.src1':'Kun Katiman','cit.src2':'Maasalikul Jinaane','cit.src3':'Kun Katiman',
    'cit.src4':'Muwahibi','cit.src5':'Kun Katiman','cit.src6':'Munawwir-us-sudûr',
// GALLERY
    'gallery.tag':'Images','gallery.title':'Gallery',
    'gallery.subtitle':'Visuals and images related to Mouridism and the spiritual heritage of Cheikh Ahmadou Bamba.',
    'gallery.p1.title':'Louga Station – August 20, 1895',
    'gallery.p1.desc':"Cheikh Ahmadou Bamba prayed at Louga station on August 20, 1895. On September 5, 1895 in Saint Louis, he was tried and deported to Gabon, leaving Senegal on September 21, 1895 aboard the vessel «Ville de Pernambouc».",
    'gallery.p2.title':'Magal of Touba',
    'gallery.p2.desc':'The Grand Magal, annual pilgrimage gathering millions of faithful in Touba.',
    'gallery.p3.title':'Darou Marnane',
    'gallery.p3.desc':"Founded by Mame Thierno on the recommendation of Serigne Touba, who resided there (1902-1903) upon his return from Gabon. On June 14, 1903, he was surrounded by colonial authorities and deported to Mauritania.",
    'gallery.p4.title':'Serigne Touba and Cheikh Ibra',
    'gallery.p4.desc':'Historic portrait of Cheikh Ahmadou Bamba and Cheikh Ibrahima Fall, pillar of Mouridism.',
    'gallery.p5.title':'Serigne Mountakha Mbacké',
    'gallery.p5.desc':'Serigne Mountakha Mbacké, Khalife General of the Mourides, spiritual guide of the community.',
    'gallery.p6.title':'Thieyene Djolof',
    'gallery.p6.desc':"Village where Cheikh Ahmadou Bamba was placed under house arrest upon his return from exile in Mauritania (1907-1912). Cheikh Abdoulahi Mbacké (Serigne Abdou Borom Deurbi) was born here.",
    'gallery.p7.title':'Darou Mousty',
    'gallery.p7.desc':"Founded by Mame Thierno Birahim Mbacké in 1912 on instructions from his brother Ahmadou Bamba. Darou Mousty is a Mouride religious city located 28 km from Touba, in the Louga region.",
    'gallery.p8.title':'Touba – Holy City',
    'gallery.p8.desc':"Founded in 1887-1888 by Cheikh Ahmadou Bamba, Touba is the capital of Mouridism. Born from a mystical vision in the Mbaffar forest, it is today the second city of Senegal.",
    // BLOG
    'blog.tag':'News','blog.title':'Mouride Blog',
    'blog.subtitle':'Articles, reflections and news on Mouride spirituality, leadership and African youth.',
    'blog.all':'All','blog.spiritualite':'Spirituality','blog.leadership':'Leadership',
    'blog.economie':'Economy','blog.jeunesse':'Youth','blog.histoire':'History',
    'blog.readmore':'Read article →',
    'blog.newsletter.title':'Stay informed of new articles',
    'blog.newsletter.desc':'Receive our best articles on Mouride spirituality every week.',
    'blog.newsletter.ph':'your@email.com','blog.newsletter.btn':'Subscribe',
    'blog.newsletter.success':'✓ Thank you! You are subscribed.',
    'blog.reactions':'Reactions','blog.comments':'Comments',
    'blog.commentBtn':'Post','blog.firstComment':'Be the first to comment ✨',
    // CONTACT
    'contact.tag':'Get in Touch','contact.title':'Contact',
    'contact.subtitle':"Let's stay in touch",
    'contact.desc':'For any questions, collaboration, or suggestions, feel free to contact us.',
    'contact.nameLabel':'Full Name','contact.namePH':'Your name',
    'contact.emailLabel':'Email','contact.subjectLabel':'Subject',
    'contact.subjectPH':'Subject of your message',
    'contact.msgLabel':'Message','contact.msgPH':'Your message...',
    'contact.send':'Send Message','contact.follow':'Follow us',
    'contact.successMsg':'Message sent successfully!',
    'contact.successSub':'We will get back to you as soon as possible.',
    // FOOTER
    'footer.links':'Quick Links',
    'footer.desc':'Étudiant Mouride Academy - Platform dedicated to transmitting the thought of Cheikh Ahmadou Bamba to the youth.',
    'footer.copy':'© 2026 Étudiant Mouride Academy | MS',
  },
};

const LangContext = createContext<LangCtx | null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  const t = (key: string): string => (T[lang]?.[key as keyof typeof T[typeof lang]] as string) ?? key
  const toggleLang = () => setLang((l: Lang) => l === 'fr' ? 'en' : 'fr')
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang(): LangCtx { return useContext(LangContext) as LangCtx }
